### ISSUE TITLE
azure-uamqp-c vs qpid-proton for c

### ISSUE THREAD

**Issue by MZDN** [Azure/azure-uamqp-c#1]
Are you planning to use azure-uamqp-c for producton instead of qpid-proton-c?

**Comment by dcristoloveanu** [comment]
Sorry for the delay.
We are planning to use uamqp for the IoTHub Device SDK (azure-iot-sdks) in the near future.

Hope this helps,
/Dan

**Comment by MZDN** [comment]
@dcristoloveanu thanks for your reply! Will you support service bus too?

**Comment by dcristoloveanu** [comment]
@MZDN We do have in plan using this in the EventHub C client (at azure-event-hubs), which is nothing else than a wrapper API on top of an underlying AMQP lib, but currently there is no plan for other SB components AFAIK (queues/topics etc).

I believe having some samples for SB should not be such a daunting task, as there is already a sample of pushing events to EventHub. A similar sample could be derived for queues and so on.

If you are asking about a complete C ServiceBus SDK, we don't have that right now (although it sounds interesting). Do you have some specifics of which components in SB are you interested in and which tasks you want to accomplish (that will help also when adding extra samples so we know which ones to add first).

**Comment by MZDN** [comment]
@dcristoloveanu many thnaks for your reply. It will be helpful to put some samples for queues/topics. Thanks!
