### ISSUE TITLE
Error when connecting to Azure IOTHub

### ISSUE THREAD

**Issue by mario19911** [Azure/azure-uamqp-c#113]
Hey guys,

we currently try to connect to an existing device of our Azure IoTHub. Unfortunately we always get an error during the SASL authentication: in sasl.outcome the code field is set to 2 indicating a system error.

The sasl authentication looks like this:
     - Username: device@sas.root.IOTHUBCMIC.azure-devices.net
     - Password: SharedAccessSignature=SharedAccessSignature sr=IOTHUBCMIC.azure-devices.net%2Fdevices%2Ftest-001&sig={sig}&se=1495780171

whereas the password is the SAS token generated by the DeviceExplorer. I got the feeling that there is some fault in our connection string, but I got no idea which one :) can somebody help me out?

Best regards,
Mario

**Comment by mario19911** [comment]
Hi @dcristoloveanu 

thank you for your fast answer :) I still hat the same problem with the username of this form. The reason seems to be the usage of SASL PLAIN - when I use the MSSBCBS authentication method it works. Do you know if an IOTHub does not allow PLAIN?

Best regards,
Mario

**Comment by dcristoloveanu** [comment]
Hi @mario19911,

I am sorry for giving you incorrect information earlier.
The username (authcid) in SASL_PLAIN for IoTHub should be
<deviceId>@sas.<iotHubName>

In your case that is
test-001@sas.IOTHUBCMIC

I just tested this and you are correct, having the fully qualified name does not work, while using the IotHub name only works fine.

Here is the documentation for it:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security

Hope this helps,
/Dan

**Comment by mario19911** [comment]
Hi @dcristoloveanu 

thank you very much, that worked perfectly fine :) 

Just another question: in my Wireshark I recognized that the IOTHub does not send any "flow" message, is this an expected behaviour?

Best regards,
Mario

**Comment by dcristoloveanu** [comment]
Hi @mario19911,

I believe IoTHub does send FLOW performatives (but when needed).
For example if I have 1000 transfers I do see a FLOW coming in:

![image](https://cloud.githubusercontent.com/assets/8507399/26230345/ff5ee72a-3bfc-11e7-8a64-1efc1785827e.png)

Can you paste the AMQP log/wireshark log in a new issues if this is a problem and I will have a look.

Cheers,
/Dan

**Comment by mario19911** [comment]
Hey @dcristoloveanu 

currently there is no problem for us, I was just wondering because QPID always sends a flow after receiving a transfer. But in that case its ok :)

Thanks for your help!

Best regards,
Mario
