### ISSUE TITLE
XMPP implementation

### ISSUE THREAD

**Issue by mario19911** [Azure/azure-uamqp-c#136]
Hey guys,

this is not an issue, it is just a question :)

I saw that you were working on a small AMQP as well as a small MQTT (umqtt) implementation that can be used in embedded systems. I just wanted to ask you if you also developed such a library for XMPP?

Best regards,
Mario

**Comment by dcristoloveanu** [comment]
Hi @mario19911,

We have not developed an XMPP library that uses the C shared utility PAL and its IO abstraction. Up to now this was not requested by anyone and it's not in the plan to be supported by any of the services around me (IoTHub, EH, etc.).

I am by far not an expert in XMPP. Seems like an implementation that uses XIO for the TCP/TLS binding should be doable, but honestly it is not on my radar as a priority :-).

If you need XMPP and a slim C library, maybe this would also work to avoid implementing everything by yourself: https://github.com/strophe/libstrophe.

If you would like however to start such a project, I would suggest creating a repo and submoduling C shared. I can provide some level of review/input related to the TCP/TLS binding if that helps you.

Cheers,
/Dan

**Comment by mario19911** [comment]
Hey @dcristoloveanu 

thank you for your fast respond. We are currently discussing about additionally implementing XMPP to be used for IoT. Therefore I just was curious if there will be an implementation available :)

Thank your for your support :)

Best regards,
Mario

**Comment by dcristoloveanu** [comment]
No worries, until next time @mario19911 :-).
