### ISSUE TITLE
small bug:  azure-uamqp-c/src/amqpvalue_to_string.c line 244

### ISSUE THREAD

**Issue by VisSpatial** [Azure/azure-uamqp-c#163]
240         case AMQP_TYPE_LONG: 
241         { 
242             char str_value[21]; 
243             uint64_t value; 
244             if (amqpvalue_get_ulong(amqp_value, &value) != 0) 

line 244 above should be:
 if (amqpvalue_get_long(amqp_value, &value) != 0)

**Comment by dcristoloveanu** [comment]
Thanks for reporting this, will issue a fix shortly.

**Comment by VisSpatial** [comment]
Thanks for your response.

Just want to encourage the team that this little library is very much useful and highly effcient:

Compare to the .Net library which take a lot space for Nuget Packages (near 100MB?), xMB dlls, and annoying vhost.exe, this is so clean and light.

it truly represented the principle what IoT solution really need to be 
(real time, light way, as what AMQP aimmed to as well).

Access Azure Table using AzureStorage C++ library (wastorage.dll and cpprestxxx.dll) was even worse: nearly GB packages, and 20MB dlls,
(and extremly slow, could take 60 seconds to fetch a single 1000 records page, never wanted to spend time to look into it about why.)

By uring the shared-c-library and hmac-sha256 from this library, now it can be done within a single 800KB exe binary with no pacakge, no dll, at all.  and it receives the 1000 records page with same query condiction (full table scan) within only 3-5 seconds on exactly same network and same PC.

Great Job, team!

**Comment by dcristoloveanu** [comment]
Thanks for the props! Always glad to hear both about issues and happy users.
I'll make sure to send this to the team.

Cheers,
/Dan

**Comment by dcristoloveanu** [comment]
A fix has been checked in.
