### ISSUE TITLE
trace_free is not thread safe

### ISSUE THREAD

**Issue by SparhawkSoftware** [Azure/azure-uamqp-c#19]
I get crashes in trace_free when I access the library simultaneously from multiple threads.
It looks like it is because trace_free is not thread safe.
Does this sound like a correct diagnosis?

**Comment by dcristoloveanu** [comment]
You are correct, trace_free is not thread safe.
If you do not need the memory trace (which has been used to measure memory usage for some scenarios), I'd say disable it with the memory_trace cmake option.
cmake .. -Dmemory_trace:bool=OFF

Let me know if this helps.

**Comment by SparhawkSoftware** [comment]
With -Dmemory_trace:bool=OFF get the crash I reported in the other thread.

**Comment by dcristoloveanu** [comment]
It seems the crash in #13 is what needs fixing, so looking at that and closing this issue.
