### ISSUE TITLE
Make device side ping user configurable 

### ISSUE THREAD

**Issue by anhashia** [Azure/azure-uamqp-c#190]
Currently it is set to **half** of what is sent by the AMQP broker in Open Frame

https://github.com/Azure/azure-uamqp-c/blob/5b3db494254b5b17ac4e7e4ceefc43150f7564b1/src/connection.c#L1589
remote_idle_timeout = (connection->remote_idle_timeout / 2)

Provide user configurable option so that user can set it other **ratio** if they don't like the default.

**Comment by bloodwine** [comment]
This enhancement would be highly useful for scenarios where the devices are on an expensive metered connection (e.g. cellular). 

This is the case of the project I am currently working on where we must **minimize bandwidth usage as much as possible** while sending infrequent telemetry events to the cloud and leaving the connection opened all of the time (to process cloud-to-device messages with a low latency). 

In that scenario, the default ratio of **1/2 * remote idle time out** means the keep alive process consumes most of the total bandwidth even when the service remote idle time out is increased to its maximum value of **25 minutes** (as referenced here : https://github.com/Azure/azure-iot-sdk-csharp/issues/46#issuecomment-334331575) .

**Comment by dcristoloveanu** [comment]
This is already checked in.
