### ISSUE TITLE
IOP Problems with ActiveMQ 5.14.1

### ISSUE THREAD

**Issue by SparhawkSoftware** [Azure/azure-uamqp-c#22]
I get this error when receiving messages from ActiveMQ:

azure-uamqp-c\src\link.c Func:_link_frame_received Line:323 Could not get the more field from the transfer performative

Note that the same version of ActiveMQ worked fine with an earlier version of uAQMP so whatever is going wrong is related to changes in the uAQMP library.

The headers in the message are as follows:

message-id: 1234567890:10
subject: ua-data
content-type: application/opcua+uajson
user-id: uAMQP 
group-id: MyDataSetWriter
group-sequence: 10
ua-class-id: MyDataSetClass
ua-metadata-node-name: MetaDataTopicName

The message body is a JSON document < 1000 bytes.

Any hints or suggestions?

**Comment by dcristoloveanu** [comment]
@SparhawkSoftware Looking at this.

**Comment by SparhawkSoftware** [comment]
Samples that replicate the problem can be found here:
https://github.com/SparhawkSoftware/UA-AnsiC

prototyping branch
prototypes/amqp

**Comment by dcristoloveanu** [comment]
This was recently introduced indeed (apologies), a fix has been submitted to the develop branch so that the more flag is optional (as it should be per spec).

Please reopen this if there are any issues with the fix.
