### ISSUE TITLE
connection stops receiving messages after a link closes

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-uamqp-c#228]
Hi there,

I'm running into some interesting behaviour and would like to confirm whether the scenario I've implemented is actually intended to be supported.

I have two message receivers running against two partitions in an event hub. They are running simultaneously and asynchronously, and they share a single CBS session and connection.

If one of these two receivers runs out of messages, it will close itself down (i.e. call destroy on both it's receiver and it's link, NOT the session or connection).
However I notice that when this happens, the other partition will stop receiving messages, even though I know there's still messages. The client hasn't hung - I can see that it's still polling the connection, however the connection just stops receiving any further data.

I intend to keep digging - but are you aware of any steps in the receiver destroy or link destroy that would prevent other links/receivers using the same connection from continuing to receive?

Thanks!

**Comment by annatisch** [comment]
On further digging in the trace logs, I have further details.
When my client closes, it sends the detach frame as expected:
'-> [DETACH]* {2,true}'

However, by the time it receives the corresponding detach from from the service, the link endpoint has already been removed. Therefore, the session detects as error:
<- [DETACH]* {2,true,NULL}
-> [END]* {* {amqp:session:unattached-handle,}}
<- [END]* {* {amqp:session:unattached-handle,,NULL}}
<- [CLOSE]* {* {amqp:not-found,The session channel '0' cannot be found in connection 'in-connection805494948(pyevent)'.,NULL}}

**Comment by annatisch** [comment]
Okay, so I tried commenting out this line and replacing it with a log message to ignore a DETACH frame from a link endpoint that has already been removed:
https://github.com/Azure/azure-uamqp-c/blob/master/src/session.c#L469

However this still doesn't completely solve the issue - because it is possible to receive additional TRANSFER frames from the detaching link in between when the DETACH frame is sent and a DETACH frame is received. These also result in generating session errors:
'-> [DETACH]* {3,true}'
'<- [TRANSFER]* {3,4,<>,0,true,false,NULL,NULL,NULL,NULL,true}'
'-> [END]* {* {amqp:session:unattached-handle,}}'
'<- [TRANSFER]* {3,5,<>,0,true,false,NULL,NULL,NULL,NULL,true}'
'-> [END]* {* {amqp:session:unattached-handle,}}'
'<- [TRANSFER]* {3,6,<>,0,true,false,NULL,NULL,NULL,NULL,true}'
'-> [END]* {* {amqp:session:unattached-handle,}}'
'<- [DETACH]* {3,true,NULL}'
'Ignoring because Link endpoint already gone.' (b'./src/vendor/azure-uamqp-c/src/session.c':b'on_frame_received':469)
'<- [END]* {* {amqp:session:unattached-handle,,NULL}}'
'<- [CLOSE]* {* {amqp:not-found,The session channel '0' cannot be found in connection 'in-connection809858870(pyevent)'.,NULL}}"

**Comment by dcristoloveanu** [comment]
@annatisch I think it should be possible to reject the transfers for a link that has been removed.
Btw thanks for looking at this, will also take a closer look at it shortly.

Thanks,
/Dan

**Comment by annatisch** [comment]
Thanks @dcristoloveanu  - it's possible a better fix for this would be to simply not remove the link endpoint until either the DETACH frame has been received or the session is closed for other reasons.

**Comment by dcristoloveanu** [comment]
Hi @annatisch 

I finally got to this one, sorry for the delay (other tasks prevented me from actually looking at these issues).

I think the core of the issue is actually the fact that link_destroy is not an async call, it is an immediate destroy. On the wire however the detach is only complete when the counterpart DETACH is received.

Ideally messagesender_close should be an async call where the user would be notified by a callback of the completion of the close. This would obviously translate in an underlying DETACH being sent and then waiting for the counterpart DETACH.

Same would apply for messagereceiver.

While in CLOSING all indications of TRANSFERs for message_receiver should still happen.
For the sender the sends should probably be blocked while closing.

How pressing is the issue? I am gauging if I should evaluate a workaround as a temporary solution or go for the full blown fix.

In the meanwhile I will get a test in for this case.

Cheers,
/Dan

**Comment by dcristoloveanu** [comment]
Test for this has been added and it is disabled as it fails.
After thinking about this just a bit more I believe we will anyhow need to handle the case when a link is destroyed without nicely waiting for it to detach.
In this case the other links on the same sessions should not be affected anyhow.

Thus it means we should track the fact that the link is detaching and basically reject the transfer for that link if it is a receiver link and limit sends for that link if it is a sender link.

The point being that this has to do done regardless of exposing the nice asynchronous APIs to the user...

I'll work on adding this state for the link endpoints and let you know how it goes.

**Comment by annatisch** [comment]
Awesome - thanks so much for taking a look! :)

**Comment by annatisch** [comment]
Thanks @dcristoloveanu - I've tried it out and it seems to be working successfully :)
I tested with a variety of prefetch settings and seems to work regardless of the messages received in between when DETACH is send and received. Great stuff!!

**Comment by dcristoloveanu** [comment]
PR #236 has been filed for this. I'll merge it in once it is reviewed.
Thanks for the validation!

**Comment by annatisch** [comment]
Fix now merged :)
