### ISSUE TITLE
transmitting to Eventhub using messagesender_send_async

### ISSUE THREAD

**Issue by ahmedawad1** [Azure/azure-uamqp-c#239]
Hi all,

I have a question regarding this sample [program](https://github.com/Azure/azure-uamqp-c/blob/master/samples/message_sender_sample/main.c) and specifically when using the 
`messagesender_send_async` I understand that this method transmits asynchronously to cloud. There is also a call back function `on_message_send_complete`  which returns the message transmission result.

I use it like this in my application:

> void onMessageSendComplete(void* context, MESSAGE_SEND_RESULT send_result)
  {
      (void)context;
          if (send_result == MESSAGE_SEND_OK)
       {
        ms_unSentMessages++;
        }
  }
      
 My question is when this method `messagesender_send_async` calls the other call back function `onMessageSendComplete` and if send_result == MESSAGE_SEND_OK condition is met, **does this actually guarantee that the message are sent to the eventhub?** 

I am asking this because here from Microsoft in this [article ](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-programming-guide) they are mentioning that transmission asynchronously to eventhub could cause lost messages when server is in error. I am wondering if there are some internal errors/server errors in the eventhub and my client (messagesender_send_async) tries to transmit, will the client detect that the messages are not accepted by the eventhub and eventually not stored inside?

Thanks
Kind regards
Ahmed

**Comment by dcristoloveanu** [comment]
Hi @ahmedawad1 

Let me try to address these one by one.
1) For the Disposition loss I see 2 options:
a) uAMQP currently will indicate the transfers that have no disposition as error'd when the connection is detected as broken. So the client side app would see that the payloads are not sent and send them again. This obviously can create duplicates and a de-dup solution has to be implemented in the layers above uAMQP.
b)There is a thing called unsettled map in the attach of a link and that could solve your problem at AMQP level. I am currently researching internally if this is obeyed by the EH broker and will come back with an update. This path would require though that uAMQP supports this (and it does not right now)

2) dowork is a way to delegate to the user the scheduling of "when should the library" do its job and execute its tasks. This is similarly done in other libraries (like libwebsockets for example) and it is rather typical in more constrained devices where one would not necessarily want to spin a thread to handle the work of the lib.
When to call do work is really your choice. A typical thing to do on a high end system is to spin a thread and call dowork every 1ms, 10ms or whatever time slice you choose.
Let's take an example:
messagesender_send_async is called with 1s timeout and immediately you enter a while (1) where you call dowork.
dowork would do all the work needed to put the TRANSFER bytes on the wire (in several calls maybe, depending on what goes on the wire, etc.) Now let's assume that no DISPOSITION comes back for this transfer. After 1s dowork would trigger the message send complete callback with TIMEOUT.

For the case you described where the connectivity is lost before even the first dowork happens, I think what you would get is that the whole handshake would fail (the socket level connection would fail opening which would propagate the error up to connection, session, etc. all the way up to message_sender which would trigger a state change callback telling you that the message sender is closed now).

messagesender_create is the function where the on_message_state_changed is passed to the message sender. The sample passes NULL there, but in the case you want to detect that connectivity loss a non-NULL callback should be passed there.

Hope this help,
/Dan

**Comment by dcristoloveanu** [comment]
Hi @ahmedawad1 
For 1) I just checked and EH does not support link resumes due to the fact that the server side would have to retain the state of each link for a potentially infinite amount of time which could create a lot of resource usage issues. Even if these resumable links would be expired after some time there is complexity that would be brought in with such a feature and the EH decision was that it is not warranted.
So even if we would put in uAMQP this feature it would still not be usable with EH.

This basically leaves only option no. 2) for you, when the transfer is indicated as complete with error by uAMQP the user code can retry if needed. Again, I want to emphasize that this creates the potential of duplicates, that need to be dealt with by some other means by the higher layers of your system. One example would be using message-id or some other property to detect duplicates when pulling data out of EH.

Hope this helps!
/Dan

**Comment by ahmedawad1** [comment]
Thank you so much Dan for your clarifications!
