### ISSUE TITLE
Use uamqp with no-microsoft brokers

### ISSUE THREAD

**Issue by rulez85** [Azure/azure-uamqp-c#24]
Hi all!

I'm trying to use azure-uamqp-c with an Apollo broker ([https://activemq.apache.org/apollo/](https://activemq.apache.org/apollo/)) running on my machine.

First question: is this even possible?

If this is the case, I'm unable to find the right way to set the parameters for the amqp connection.
I was able to create a simple working example in C# by using the AMQP.Net Lite library (https://github.com/Azure/amqpnetlite) to send a message to the Apollo broker:

        

            // Connect to the Apollo broker on localhost:5672
            var address = new Address("amqp://admin:password@127.0.0.1:5672");
            var connection = new Connection(address);
            // Begin an AMQP session
            var session = new Session(connection);
            // Create an AMQP link to send data and attach it to the "testQueue" queue in Apollo
            var sender = new SenderLink(session, "senderLink", "queue://testQueue");
            // Create a new message to be sent
            var message = new Message("Test message from AMQP Net Lite");
            // Send the message
            await sender.SendAsync(message);
            sendTime = DateTime.Now;
        

I'm at a loss as to where specify the "queue://testQueue" parameter in uamqp.
In the uaqmp examples linking is carried out using the "sender-link" string, which I assume is roughly the same as the "senderLink" string in the sample C# code. Am I correct?

Thanks in andvance
Nicola

**Comment by dcristoloveanu** [comment]
Hi @rulez85,

From what I can see "queue://testQueue" is the target address for the sender link.
In uamqp, one can set the source and target address when the link is created (similar to what is done in the message_sender sample).

		AMQP_VALUE source = messaging_create_source("someLocalSourceAddress");
		AMQP_VALUE target = messaging_create_target("queue://testQueue");
		link = link_create(session, "sender-link", role_sender, source, target);

"sender-link" is simply the link name.

Hope this helps,
/Dan

**Comment by rulez85** [comment]
Thanks for your fast reply!

I tried to set "queue://testQueue" in the target address of the sender link but it didn't work.

Here is the code:
```
assert (platform_init() == 0);

SASL_PLAIN_CONFIG saslPlainConfig;
saslPlainConfig.authcid = "admin";// configuration.AuthData.Username.c_str();
saslPlainConfig.passwd = "password"; //  configuration.AuthData.Password.c_str();
saslPlainConfig.authzid = NULL;
SASL_MECHANISM_HANDLE saslMechanismHandle = saslmechanism_create(saslplain_get_interface(), &saslPlainConfig);

/* create the TLS IO */
TLSIO_CONFIG tlsIOConfig;
tlsIOConfig.hostname = connectionHost.c_str();
tlsIOConfig.port = connectionPort;

const IO_INTERFACE_DESCRIPTION* tlsio_interface = platform_get_default_tlsio();
XIO_HANDLE tlsIO = xio_create(tlsio_interface, &tlsIOConfig);

/* create the SASL client IO using the TLS IO */
SASLCLIENTIO_CONFIG saslIOConfig;
saslIOConfig.underlying_io = tlsIO;
saslIOConfig.sasl_mechanism = saslMechanismHandle;
XIO_HANDLE saslIO = xio_create(saslclientio_get_interface_description(), &saslIOConfig);

CONNECTION_HANDLE connectionHandle = connection_create2(saslIO, "127.0.0.1", "some",
	NULL, NULL, onConnectionStateChanged, saslIO, on_io_error, NULL);
	
SESSION_HANDLE sessionHandle = session_create(connectionHandle, on_link_attached, connectionHandle);
session_set_incoming_window(sessionHandle, 2147483647);
session_set_outgoing_window(sessionHandle, 2);
	
// NOTE: not using CBS for apollo broker

AMQP_VALUE source = messaging_create_source("ingress");
AMQP_VALUE target = messaging_create_target("amqp://admin:password@127.0.0.1:5672"); // does no work
//AMQP_VALUE target = messaging_create_target("amqp://127.0.0.1:5672"); // does not work too
//AMQP_VALUE target = messaging_create_target("queue://testQueue"); // does not work too

linkHandle = link_create(sessionHandle, "sender-link", role_sender, source, target);
link_set_max_message_size(linkHandle, MAX_MESSAGE_SIZE);
amqpvalue_destroy(source);
amqpvalue_destroy(target);

messageSenderHandle = messagesender_create(linkHandle, onMessageSenderStateChanged, NULL);

assert (messagesender_open(messageSenderHandle) == 0);

// NOTE: messageSenderOpened and errorOpeningSender are set from onMessageSenderStateChanged callback
while (!messageSenderOpened)
{
	connection_dowork(connectionHandle);

	assert(connected); // set by onConnectionStateChanged
	
	if (errorOpeningSender)
		break;
}

// ... other code
```
The main problem is that I cannot find a way to catch error in the while loop after message sender open.
No callback is called during the while loop. Is there a way to know that message sender cannot be opened with these parameters? 

Thanks in advance,

Nicola

**Comment by ppatierno** [comment]
I'm not an Apollo expert and a uAMQP as well but I know the AMQP protocol :-) ... 
What I see here is that you are setting a TLS layer but then connecting to a NON TLS port (the default 5672) on Apollo.
Can you catch the AMQP traffic using WireShark just to understand if something happens during the TLS handshake or if it works where is the problem in the AMQP messages exchange.

**Comment by rulez85** [comment]
Hi @ppatierno!
You are right (even if I think it is a problem not to have a way to break from the while loop).
I changed my code using SOCKETIO_CONFIG instead of TLSIO_CONFIG (copying from uamqp example "local_client_sample"):

```
    SOCKETIO_CONFIG socketio_config;
    socketio_config.hostname = connectionHost.c_str();
    socketio_config.port = connectionPort;
    socketio_config.accepted_socket = NULL;
    ioHandle = xio_create(socketio_get_interface_description(), &socketio_config);
   
    CONNECTION_HANDLE connectionHandle = connection_create2(ioHandle , "127.0.0.1", "some",
	NULL, NULL, onConnectionStateChanged, saslIO, on_io_error, NULL);
```

but now I get the following error occurring in the calls to the connection_dowork method in the while loop:

`Error: Time:Fri Dec 23 14:02:21 2016 File:C:\Dev\ThirdParty\azure-uamqp-c\c-utility\adapters\socketio_win32.c Func:_socketio_open Line:259 Failure: socket state is not closed.`

Any idea on how to solve this error?

Thanks in advance

**Comment by acartcat** [comment]
Hi,
   I had a similar issue trying to connect to the Apache Qpid C++ broker.  I used the develop branch but the OPEN was still failing on the call to open_get_max_frame_size in connection.c.  After looking at your code in amqp_definitions.c I added the check for AMQP_TYPE_NULL in the open_get_max_frame function and all is working fine.

Cheers

**Comment by acartcat** [comment]
```C
int open_get_max_frame_size(OPEN_HANDLE open, uint32_t* max_frame_size_value)
{
	int result;
	if (open == NULL)
	{
		result = __LINE__;
	}
	else
	{
		OPEN_INSTANCE* open_instance = (OPEN_INSTANCE*)open;
		AMQP_VALUE item_value = amqpvalue_get_composite_item_in_place(open_instance->composite_value, 2);
		if (item_value == NULL)
		{
			*max_frame_size_value = 4294967295;
            		result = 0;
		}
		else
		{			
			if (amqpvalue_get_uint(item_value, max_frame_size_value) != 0)
			{
				if (amqpvalue_get_type(item_value) != AMQP_TYPE_NULL)
				{
					result = __LINE__;
				}
				else
				{
					result = 0;
				}
				
			}
			else
			{
				result = 0;
			}
		}
	}
	return result;
}
```

**Comment by dcristoloveanu** [comment]
@acartcat 

Thanks for the change, in the process of integrating it.

Cheers,
/Dan

**Comment by dcristoloveanu** [comment]
This has been checked in into develop.

Thanks again!
/Dan
