### ISSUE TITLE
Connection close segfault with multiple sessions

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-uamqp-c#245]
Hi @dcristoloveanu - I'm seeing an error in one of my async samples that I thought I would run by you for some advice.

I'm running two receivers, each with their own Session on a single connection.
I close one receiver, its Link, and its Session, before closing the 2nd receiver, its Link and its Session, then finally destroy the connection.

However I'm getting a segmentation fault in the connection_close method - specifically, it's occurring during the connection state change callback for endpoints:
https://github.com/Azure/azure-uamqp-c/blob/master/src/connection.c#L113

I think the connection thinks it still has an endpoint reference that has already been cleaned up.
I see the connections endpoints should be cleaned up during the shutdown of each Session:
https://github.com/Azure/azure-uamqp-c/blob/master/src/connection.c#L1968

Though going through this method - I'd like to clarify the behaviour. It seems that the endpoint will only be destroyed if:
a) The endpoint count is 1 (i.e. it's the last endpoint) or
b) The endpoint count is not the first in a list of 2 or more.

Why do we not clean up the endpoint if it's the first in the connection endpoints list?
Does the connection need to hold on to this "index 0" endpoint in order to send the CLOSE frame?
I found by removing the ` && (i > 0)` for the IF statement, my code ran without crashing.

Alternatively, I was also able to stop the crashing by only freeing the ENDPOINT_HANDLE if it was one of the endpoints removed (however this approach would seem to introduce a memory leak?):
```
        /* Codes_S_R_S_CONNECTION_01_130: [The outgoing channel associated with the endpoint shall be released by removing the endpoint from the endpoint list.] */
        /* Codes_S_R_S_CONNECTION_01_131: [Any incoming channel number associated with the endpoint shall be released.] */
        if ((i < connection->endpoint_count) && (i > 0))
        {
            ENDPOINT_HANDLE* new_endpoints;
            (void)memmove(connection->endpoints + i, connection->endpoints + i + 1, sizeof(ENDPOINT_HANDLE) * (connection->endpoint_count - i - 1));

            new_endpoints = (ENDPOINT_HANDLE*)realloc(connection->endpoints, (connection->endpoint_count - 1) * sizeof(ENDPOINT_HANDLE));
            if (new_endpoints != NULL)
            {
                connection->endpoints = new_endpoints;
            }

            connection->endpoint_count--;
            free(endpoint);
        }
        else if (connection->endpoint_count == 1)
        {
            free(connection->endpoints);
            connection->endpoints = NULL;
            connection->endpoint_count = 0;
            free(endpoint);
        }
    }
```

So - in conclusion - if there any pattern you can think of in my process of deconstructing receivers -> links -> sessions -> connection that would result in the connection endpoint being prematurely cleaned up without the connection being updated appropriately?

**Comment by annatisch** [comment]
Ah - so I actually just read the comment that says:
`Any incoming channel number associated with the endpoint shall be released.`

Does this mean that endpoint "index 0" is an "incoming channel number"?

**Comment by annatisch** [comment]
I have a new theory.
When the Session starts the endpoint, it passes in the Session itself as the callback_context:
https://github.com/Azure/azure-uamqp-c/blob/master/src/session.c#L844

However when the Session is destroyed, I guess that context is lost, but the incoming channel endpoint that references that context is not removed from the connection endpoints.
The in the connection_set_state function, it tries to pass the callback_context into the state change callback:
https://github.com/Azure/azure-uamqp-c/blob/master/src/connection.c#L113

Does that seem at all plausible?

**Comment by annatisch** [comment]
I should add some context - this error is only happening when the receivers/link/sessions are shutdown due to a link redirect DETACH frame. 

I have another sample with receivers/links/sessions sharing a connection that shuts down on timeout and that has no issues.

**Comment by dcristoloveanu** [comment]
Thanks @annatisch for the context, let me have a look and I'll come back with what I find.

Cheers,
/Dan

**Comment by dcristoloveanu** [comment]
Hi @annatisch 

I finally got to start looking at this issue, I am building a repro for it in the local tests. What would help me in case if you have it is one of your logs for it.

Thanks,
/Dan

**Comment by annatisch** [comment]
Sure thing - I'll just run the test again.

**Comment by dcristoloveanu** [comment]
Thanks!

Wrote a test for it and indeed I am definitely getting the same AV. Working on the fix based on your comments!

/Dan

**Comment by dcristoloveanu** [comment]
I just submitted #248, the cleanup of the endpoint was weirdly written indeed as you noticed in your comments. I do not remember doing that, I was very surprised at it also, but hey, who knows, it was probably me :-).

Let me know if this solves your AV.

/Dan

**Comment by annatisch** [comment]
Thanks so much!
The test is certainly now running without crashing :)

Though I am still seeing a "Cannot find session endpoint" error - is this important?

```
2018-07-03 13:42:36,400 uamqp.c_uamqp INFO     b'-> [DETACH]* {0,true}'
2018-07-03 13:42:36,401 uamqp.c_uamqp INFO     b'-> [END]* {}'
2018-07-03 13:42:36,419 uamqp.c_uamqp INFO     b'<- [DETACH]* {0,true,NULL}'
2018-07-03 13:42:36,419 uamqp.c_uamqp ERROR    b'Cannot find session endpoint for channel 0' (b'C:\\Users\\antisch\\Documents\\GitHub\\azure-uamqp-python\\src\\vendor\\azure-uamqp-c\\src\\connection.c':b'find_session_endpoint_by_incoming_channel':618)
2018-07-03 13:42:36,420 uamqp.c_uamqp ERROR    b'Cannot find session endpoint for channel 0' (b'C:\\Users\\antisch\\Documents\\GitHub\\azure-uamqp-python\\src\\vendor\\azure-uamqp-c\\src\\connection.c':b'on_amqp_frame_received':1067)
2018-07-03 13:42:36,439 uamqp.c_uamqp INFO     b'<- [END]* {NULL}'
2018-07-03 13:42:36,439 uamqp.c_uamqp ERROR    b'Cannot find session endpoint for channel 0' (b'C:\\Users\\antisch\\Documents\\GitHub\\azure-uamqp-python\\src\\vendor\\azure-uamqp-c\\src\\connection.c':b'find_session_endpoint_by_incoming_channel':618)
2018-07-03 13:42:36,440 uamqp.c_uamqp ERROR    b'Cannot find session endpoint for channel 0' (b'C:\\Users\\antisch\\Documents\\GitHub\\azure-uamqp-python\\src\\vendor\\azure-uamqp-c\\src\\connection.c':b'on_amqp_frame_received':1067)
```

**Comment by dcristoloveanu** [comment]
This is because the Detach performatives are received after we have discarded everything related to the session. I believe this should not matter as the session is ended anyhow.

**Comment by dcristoloveanu** [comment]
This should be in master now.
Let me know if you still have issues with it!

Cheers,
/Dan

**Comment by annatisch** [comment]
Awesome thank you!
