### ISSUE TITLE
Memory leak in sender debug logging

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-uamqp-c#246]
There appears to be some kind of memory leak in the `log_message_chunk` function:
https://github.com/Azure/azure-uamqp-c/blob/master/src/message_sender.c#L162

If I run a sender continuously with debug logs on the memory steadily climbs - but _only if_ my message has one of the additional sections added (i.e. header, or properties, or annotations etc).

This logging function actually crashes on my OSX build.

I tried commenting out my custom Python logging function which seems to make no difference, so I don't think the issue is in the Python bindings.
I've commented out this function in my builds for now.

Thanks!

**Comment by dcristoloveanu** [comment]
Let me have a look. Btw, best tool I have found for now for Windows to track memory leaks is VLD. And of course Linux is Valgrind. As a matter of fact all the tests that do run in the gated build run with Valgrind on, which will catch the leaks.

I'll write a new test which uses all header properties and annotations and see if we have any leaks there. Thanks for reporting it.

Cheers,
/Dan

**Comment by annatisch** [comment]
Thanks!
Yes I've been using Valgrind + docker from time to time - though it's a bit noisy when running with Python because python implements it's own malloc, which valgrind can't track be default. 

Just to be clear - the leak only exists when debug trace is turned on. So shouldn't affect production workflows that will actually be running for long periods of time.

**Comment by dcristoloveanu** [comment]
@annatisch 

I've posted the PR fixing this. It was due to the macro P_OR_NULL, which expands to evaluating twice the value that we attempt to print.
I've added a test that turns on tracing and runs in the gated build so this should not come back.

Cheers,
/Dan

**Comment by dcristoloveanu** [comment]
This should be fixed now in the latest master.

Cheers,
/Dan
