### ISSUE TITLE
Fix clang warnings

### ISSUE THREAD

**Issue by damonbarry** [Azure/azure-uamqp-c#26]
If I try to build azure-uamqp-c with clang, I get lots of warnings (and if I fix some of them, more appear).

azure-uamqp-c should compile cleanly with clang.

**Comment by dcristoloveanu** [comment]
@damonbarry I'll have a look at this shortly.

Thanks,
/Dan

**Comment by dcristoloveanu** [comment]
A fix has been checked in to the master branch.
