### ISSUE TITLE
Error with empty Max-Frame-Size

### ISSUE THREAD

**Issue by mario19911** [Azure/azure-uamqp-c#29]
Hey guys,

according to the AMQP specifiction (http://www.amqp.org/sites/amqp.org/files/amqp.pdf) at page 54, the field max-frame-size is not mandatory. In that case the AMQP-Type NULL is used for the transmission of this value. However, the function get_max_frame_size in amqp_definitions.c returns an error in that case.

I think the if statement should be the other way round: when the type is NULL, the max-frame-size should be set to 4294967295u, otherwise an error shall be returned.

**Comment by dcristoloveanu** [comment]
Hi @mario19911

You are perfectly right, will have a fix for this very soon.

Thanks,
/Dan

**Comment by dcristoloveanu** [comment]
Hi @mario19911,

A fis is on the way in PR #31.

Thanks,
/Dan

**Comment by dcristoloveanu** [comment]
The fix has been checked in to master.

Thanks!
/Dan
