### ISSUE TITLE
Missing initialization of connection->last_frame_received_time

### ISSUE THREAD

**Issue by mario19911** [Azure/azure-uamqp-c#30]
Hey Guys,

I think found another small issue in connection.c. In the function connection_handle_deadlines, the time until the configured idle timeout expires is calculated from the current milliseconds and connection->last_frame_received_time. The problem is that connection->last_frame_received_time is not initialized in connection_create2 which results in "No frame received for the idle timeout" when an idle timeout was specified. To fix this it should be enough to use calloc instead of malloc in the function connection_create2, right?

Best regards,
Mario

**Comment by dcristoloveanu** [comment]
@mario19911 Will have a look at this one too shorty. Stay tuned.

**Comment by dcristoloveanu** [comment]
@mario19911 Btw, if you already have the fix, feel free to fire a PR and I'll review and merge in if OK.

Thanks,
/Dan

**Comment by mario19911** [comment]
@dcristoloveanu I added a new pull request for this issue.

Best regards,
Mario

**Comment by dcristoloveanu** [comment]
@mario19911 

I created PR #33 which initializes the last received frame time and last sent frame time with the value obtained from the tick counter.

Thanks,
/Dan

**Comment by dcristoloveanu** [comment]
Hi @mario19911 

I have checked in the fix to the master branch, can you please check if this resolves your issue?

Thanks,
/Dan
