### ISSUE TITLE
uamqp to connect rabbitmq message broker.

### ISSUE THREAD

**Issue by ssdbest** [Azure/azure-uamqp-c#344]
I would like to know if i can use uamqp library to interact with rabbitmq message broker. RX is simple queue based communication and TX is topic exchange (rabbitmq concept: https://www.rabbitmq.com/tutorials/tutorial-three-python.html) based communication. Any documentation or sample code would be helpful.

**Comment by Counterfly** [comment]
uamqp uses the AMQP 1-0+ protocol. rabbitMQ runs on the AMQP 0.9 protocol version so i don't think uamqp would work

**Comment by ssdbest** [comment]
Added AMQP1.0 support to rabbitmq using plugin. Now we are able communicate with rabbitmq broker.
