### ISSUE TITLE
Accessing information max-message-size

### ISSUE THREAD

**Issue by mario19911** [Azure/azure-uamqp-c#98]
Hey guys,

we are currently testing our usage of the implementation with the broker of opcfoundation-prototyping.servicebus.windows.net. In his attach message, this broker sends a max-message-size of 65536. When the sent data exceeds this value, an link-error "max-message-size-exceeded" should arise according to the AMQP specification. In that case it is necessary to implement a segmentation mechanism in the application using your AMQP stack.

Currently the max-message-size is stored nowhere in the link structure such that it can be read by the application. Is this a mistake or are there other ways to access the max-message-size information sent by the broker?

Best regards,
Mario

**Comment by dcristoloveanu** [comment]
Hi @mario19911,

I agree this should get exposed. I'll add a getter to link soon.

Thanks,
/Dan

**Comment by dcristoloveanu** [comment]
Hi @mario19911 

I filed #100, as far as I understand this is what would help you to segment at the layer above link/message_sender.

Let me know if this would solve your issue.

Thanks,
/Dan

**Comment by mario19911** [comment]
Hi @dcristoloveanu 

thanks this looks fine :) I will try it out as soon as possible.

Best regards,
Mario

**Comment by dcristoloveanu** [comment]
@mario19911 

Good to know this is what you were looking for. Once it's reviewed I'll commit it.

Thanks,
/Dan

**Comment by dcristoloveanu** [comment]
@mario19911 

The fix for this was checked in to master. Let me know if you still have any issues with this.

Cheers,
/Dan
